services:
  app:
    build: .
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysql
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-news_scraper}
      MYSQL_USER: ${DB_USER:-scraper_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-scraper_pass}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
